# Generated by Django 4.2.4 on 2023-09-04 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanagerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('descr', models.TextField()),
                ('duedate', models.DateTimeField()),
                ('prior', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('not completed', 'not completed'), ('completed', 'completed')], default='not completed', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanagerapp.task_manager_login')),
            ],
        ),
    ]
